# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'w_battery.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BatteryForm(object):
    def setupUi(self, BatteryForm):
        BatteryForm.setObjectName("BatteryForm")
        BatteryForm.resize(941, 631)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(BatteryForm)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(BatteryForm)
        self.label_6.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 22px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:9px;\n"
"    background:rgba(66, 195, 255, 0);\n"
"    color: rgb(26, 115,232);\n"
"}\n"
"")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.pbBat1 = QtWidgets.QProgressBar(BatteryForm)
        self.pbBat1.setMinimumSize(QtCore.QSize(0, 40))
        self.pbBat1.setProperty("value", 24)
        self.pbBat1.setTextVisible(False)
        self.pbBat1.setObjectName("pbBat1")
        self.horizontalLayout_12.addWidget(self.pbBat1)
        self.lblBat1 = QtWidgets.QLabel(BatteryForm)
        self.lblBat1.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 22px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:9px;\n"
"    background:rgba(66, 195, 255, 0);\n"
"    color: rgb(26, 115,232);\n"
"}\n"
"")
        self.lblBat1.setObjectName("lblBat1")
        self.horizontalLayout_12.addWidget(self.lblBat1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.label_7 = QtWidgets.QLabel(BatteryForm)
        self.label_7.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 22px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:9px;\n"
"    background:rgba(66, 195, 255, 0);\n"
"    color: rgb(26, 115,232);\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.pbBat2 = QtWidgets.QProgressBar(BatteryForm)
        self.pbBat2.setMinimumSize(QtCore.QSize(0, 40))
        self.pbBat2.setProperty("value", 24)
        self.pbBat2.setTextVisible(False)
        self.pbBat2.setObjectName("pbBat2")
        self.horizontalLayout_11.addWidget(self.pbBat2)
        self.lblBat2 = QtWidgets.QLabel(BatteryForm)
        self.lblBat2.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 22px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:9px;\n"
"    background:rgba(66, 195, 255, 0);\n"
"    color: rgb(26, 115,232);\n"
"}\n"
"")
        self.lblBat2.setObjectName("lblBat2")
        self.horizontalLayout_11.addWidget(self.lblBat2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.label_8 = QtWidgets.QLabel(BatteryForm)
        self.label_8.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 22px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:9px;\n"
"    background:rgba(66, 195, 255, 0);\n"
"    color: rgb(26, 115,232);\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.pbBat3 = QtWidgets.QProgressBar(BatteryForm)
        self.pbBat3.setMinimumSize(QtCore.QSize(0, 40))
        self.pbBat3.setProperty("value", 24)
        self.pbBat3.setTextVisible(False)
        self.pbBat3.setObjectName("pbBat3")
        self.horizontalLayout_10.addWidget(self.pbBat3)
        self.lblBat3 = QtWidgets.QLabel(BatteryForm)
        self.lblBat3.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 22px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:9px;\n"
"    background:rgba(66, 195, 255, 0);\n"
"    color: rgb(26, 115,232);\n"
"}\n"
"")
        self.lblBat3.setObjectName("lblBat3")
        self.horizontalLayout_10.addWidget(self.lblBat3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.label_9 = QtWidgets.QLabel(BatteryForm)
        self.label_9.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 22px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:9px;\n"
"    background:rgba(66, 195, 255, 0);\n"
"    color: rgb(26, 115,232);\n"
"}\n"
"")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.pbLight = QtWidgets.QProgressBar(BatteryForm)
        self.pbLight.setMinimumSize(QtCore.QSize(0, 40))
        self.pbLight.setStyleSheet("QProgressBar{ color: rgb(0, 255, 255); font:12pt; border-radius:2px; text-align:center; border:none; background-color: rgba(215, 215, 215,100);} \n"
"")
        self.pbLight.setProperty("value", 24)
        self.pbLight.setTextVisible(False)
        self.pbLight.setObjectName("pbLight")
        self.horizontalLayout_9.addWidget(self.pbLight)
        self.lblLight1 = QtWidgets.QLabel(BatteryForm)
        self.lblLight1.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 22px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:9px;\n"
"    background:rgba(66, 195, 255, 0);\n"
"    color: rgb(26, 115,232);\n"
"}\n"
"")
        self.lblLight1.setObjectName("lblLight1")
        self.horizontalLayout_9.addWidget(self.lblLight1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(BatteryForm)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.cmbPort = QtWidgets.QComboBox(self.groupBox)
        self.cmbPort.setObjectName("cmbPort")
        self.horizontalLayout_8.addWidget(self.cmbPort)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.cmbBaudRate = QtWidgets.QComboBox(self.groupBox)
        self.cmbBaudRate.setObjectName("cmbBaudRate")
        self.cmbBaudRate.addItem("")
        self.cmbBaudRate.addItem("")
        self.cmbBaudRate.addItem("")
        self.cmbBaudRate.addItem("")
        self.cmbBaudRate.addItem("")
        self.cmbBaudRate.addItem("")
        self.horizontalLayout_7.addWidget(self.cmbBaudRate)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.cmbDataBits = QtWidgets.QComboBox(self.groupBox)
        self.cmbDataBits.setObjectName("cmbDataBits")
        self.cmbDataBits.addItem("")
        self.cmbDataBits.addItem("")
        self.horizontalLayout_6.addWidget(self.cmbDataBits)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.cmbParity = QtWidgets.QComboBox(self.groupBox)
        self.cmbParity.setObjectName("cmbParity")
        self.cmbParity.addItem("")
        self.cmbParity.addItem("")
        self.cmbParity.addItem("")
        self.horizontalLayout_5.addWidget(self.cmbParity)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.cmbStopBits = QtWidgets.QComboBox(self.groupBox)
        self.cmbStopBits.setObjectName("cmbStopBits")
        self.cmbStopBits.addItem("")
        self.cmbStopBits.addItem("")
        self.cmbStopBits.addItem("")
        self.horizontalLayout_4.addWidget(self.cmbStopBits)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.btnPort = QtWidgets.QPushButton(self.groupBox)
        self.btnPort.setStyleSheet("QPushButton\n"
"{\n"
"    font-size: 22px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:9px;\n"
"    background:rgba(122, 126, 132, 100);\n"
"    color: rgb(26, 115,232);\n"
"}\n"
"")
        self.btnPort.setObjectName("btnPort")
        self.horizontalLayout_3.addWidget(self.btnPort)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2.setStretch(0, 7)
        self.horizontalLayout_2.setStretch(1, 3)

        self.retranslateUi(BatteryForm)
        QtCore.QMetaObject.connectSlotsByName(BatteryForm)

    def retranslateUi(self, BatteryForm):
        _translate = QtCore.QCoreApplication.translate
        BatteryForm.setWindowTitle(_translate("BatteryForm", "Form"))
        self.label_6.setText(_translate("BatteryForm", "电池1"))
        self.lblBat1.setText(_translate("BatteryForm", "TextLabel"))
        self.label_7.setText(_translate("BatteryForm", "电池2"))
        self.lblBat2.setText(_translate("BatteryForm", "TextLabel"))
        self.label_8.setText(_translate("BatteryForm", "电池3"))
        self.lblBat3.setText(_translate("BatteryForm", "TextLabel"))
        self.label_9.setText(_translate("BatteryForm", "亮度 "))
        self.lblLight1.setText(_translate("BatteryForm", "TextLabel"))
        self.groupBox.setTitle(_translate("BatteryForm", "参数"))
        self.label.setText(_translate("BatteryForm", "串口"))
        self.label_2.setText(_translate("BatteryForm", "波特率"))
        self.cmbBaudRate.setItemText(0, _translate("BatteryForm", "4800"))
        self.cmbBaudRate.setItemText(1, _translate("BatteryForm", "9600"))
        self.cmbBaudRate.setItemText(2, _translate("BatteryForm", "19200"))
        self.cmbBaudRate.setItemText(3, _translate("BatteryForm", "38400"))
        self.cmbBaudRate.setItemText(4, _translate("BatteryForm", "57600"))
        self.cmbBaudRate.setItemText(5, _translate("BatteryForm", "115200"))
        self.label_3.setText(_translate("BatteryForm", "数据位"))
        self.cmbDataBits.setItemText(0, _translate("BatteryForm", "8"))
        self.cmbDataBits.setItemText(1, _translate("BatteryForm", "7"))
        self.label_4.setText(_translate("BatteryForm", "校验位"))
        self.cmbParity.setItemText(0, _translate("BatteryForm", "None"))
        self.cmbParity.setItemText(1, _translate("BatteryForm", "Even"))
        self.cmbParity.setItemText(2, _translate("BatteryForm", "Odd"))
        self.label_5.setText(_translate("BatteryForm", "停止位"))
        self.cmbStopBits.setItemText(0, _translate("BatteryForm", "1"))
        self.cmbStopBits.setItemText(1, _translate("BatteryForm", "1.5"))
        self.cmbStopBits.setItemText(2, _translate("BatteryForm", "2"))
        self.btnPort.setText(_translate("BatteryForm", "打开串口"))
