# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'w_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(945, 714)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tabData = QtWidgets.QWidget()
        self.tabData.setObjectName("tabData")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabData)
        self.verticalLayout.setObjectName("verticalLayout")
        self.data_vLayout = QtWidgets.QVBoxLayout()
        self.data_vLayout.setObjectName("data_vLayout")
        self.verticalLayout.addLayout(self.data_vLayout)
        self.tabWidget.addTab(self.tabData, "")
        self.tabSetup = QtWidgets.QWidget()
        self.tabSetup.setObjectName("tabSetup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabSetup)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.setup_vLayout = QtWidgets.QVBoxLayout()
        self.setup_vLayout.setObjectName("setup_vLayout")
        self.verticalLayout_3.addLayout(self.setup_vLayout)
        self.tabWidget.addTab(self.tabSetup, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 945, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabData), _translate("MainWindow", "数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSetup), _translate("MainWindow", "设置"))
